### ISSUE TITLE
Linux: Not working on fuse/gocryptfs

### ISSUE THREAD

**Issue by krumelmonster** [SpartanJ/efsw#102]
efsw wrongly detects my gocryptfs directory as a **remote** fuse filesystem and therefore refuses to use inotify although it would work.

I believe the problem lies in the isLocalFUSEDirectory function

src/efsw/platform/posix/FileSystemImpl.cpp:181
```
                return ( !devicePath.empty() && isNTFS( devicePath ) );
```

Where for my fs `devicePath.empty()` is false as should be but `isNTFS( devicePath )` is also false, obiously. Changing this line to

src/efsw/platform/posix/FileSystemImpl.cpp:181
```
                return ( !devicePath.empty() || isNTFS( devicePath ) );
```

solves my problems, however I'm not sure what the purpose of the isNTFS function is in the first place.

**Comment by SpartanJ** [comment]
The problem is with local FUSE mounts. As far as I know and remember there's no reliable way to know if inotify will work with a FUSE mount, I only allowed to use inotify with ntfs-3g since I was 100% sure that worked. I just changed this approach, I'll assume that any FUSE file system with a local mount point will work with inofity. I'll investigate further if this is the case, but for the moment I'll enable this feature. I'm not sure why the generic file watcher didn't work for this use case, I'll have to take a look, I'm not familiar with gocryptfs.
Thanks for reporting this issue!
