### ISSUE TITLE
First renaming does not generate an event on Windows

### ISSUE THREAD

**Issue by merwaaan** [SpartanJ/efsw#111]
Hi,
It seems that the `Actions::Moved` event is not triggered the very first time a watched file is renamed **when we use the Win32 watcher**.

Steps to reproduce the issue:
- Use the test project to watch some folder
- Rename a file in the folder -> no `Moved` events **(but we get a `Modified` event for the parent folder)**
- Rename the file again or rename another file -> now we get a `Moved` + a `Modified` as expected
- Then it works fine

Please note that this does NOT happen with the generic watcher implementation: instead it triggers `Add` and `Delete` events but at least it does not miss the first one.

**Comment by merwaaan** [comment]
Additional investigation shows that this actually happens **when the file is not a direct child of the watched folder**.

**Comment by SpartanJ** [comment]
Hi! Thanks for reporting this! The issue isn't exactly what you describe but it's pretty close.
The exact issue is: the first time that occurs a file change since listening for changes from the file system, for some reason the OS is only reporting the folder change and not any file change, but only for the first time, and only when the change happened from a sub-directory of the originally watched directory. I'm currently investigating if there's an actual easy fix or I have to change the way the library watch folders recusivelly.

**Comment by SpartanJ** [comment]
@merwaaan let me know if this fixes the issue for you.

**Comment by merwaaan** [comment]
Thanks for the quick reply @SpartanJ !
I ran a few tests and renaming in sub-directories now works consistently.

However moving files in and from from sub-directories still has the same issue (Either the Add or Delete event is missing).

**Comment by merwaaan** [comment]
Your latests commits have fixed the issue. Thanks! 😀

Another issue that I just noticed is that copying a directory that contains a few files to the watched directory only generates an Add event for the copied directory and none for the files that it contains. I'm not sure if this is a bug or the expected behavior though.

**Comment by SpartanJ** [comment]
Great to hear! I had to make some core changes, now should be much more precise. I'll keep this issue open for a couple of days while I continue testing them.

Regarding the other issue: that's the expected behavior, in that case, there are no added files, those files are already created, it's just a directory movement. In that case, you'll need to scan the new directory and add those files.
